---

root: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 6
  sourceType: 'module'

env:
  es6: true
  node: true

rules:
  max-len: ['error', 80, 4, {ignoreUrls: true, ignorePattern: '^import '}]
  indent: [2, 2, {SwitchCase: 1}]
  quotes: [2, 'single']
  linebreak-style: [2, 'unix']
  semi: [2, 'never']
  space-before-function-paren: [2, 'always']
  prefer-template: [2]
  space-before-blocks: [2, 'always']
  no-trailing-spaces: [2]
  operator-linebreak: [2, 'before']
  dot-location: [2, 'property']
  eqeqeq: [2]
  curly: [2, 'all']
  no-unneeded-ternary: [2, {defaultAssignment: false}]
  no-console: [2, {allow: ['warn', 'error']}]
